### ISSUE TITLE
send help

### ISSUE THREAD

**Issue by SmellySteve** [themoonisacheese/2bored2wait#130]
```
$ events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:25566
    at Server.setupListenHandle [as _listen2] (net.js:1317:16)
    at listenInCluster (net.js:1365:12)
    at doListen (net.js:1502:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (/Users/banbutton/2bored2wait/node_modules/minecraft-protocol/src/server.js:45:12)
    at Server.emit (events.js:314:20)
    at emitErrorNT (net.js:1344:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 25566
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/banbutton/.npm/_logs/2020-10-19T13_17_03_862Z-debug.log
```

**Comment by MrGeorgen** [comment]
Can you provide the 2bored2wait.log file?

**Comment by JulioC** [comment]
It appears the server is already started:

> Error: listen EADDRINUSE: address already in use 0.0.0.0:25566

Maybe there was a dead process of `node` running

**Comment by YeetyDankEngine** [comment]
Are you using the latest 2bored2wait?
