### ISSUE TITLE
Server Brand Must Not be Null?

### ISSUE THREAD

**Issue by AnonymouseCow** [themoonisacheese/2bored2wait#147]
Hey there! So, this is my first time using 2b2w and I tried to join the queue server (localhost:25566) and it crashed Minecraft and gave me this error:

```
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: mc.player.serverBrand must not be null
Exit Code: 255
```
I checked the extended logs and it appears that kami blue caused the issue.
I removed it and all worked fine.
Although I use kami blue as one of my main clients on 2b2t, is there any way to fix this issue?

```
java.lang.IllegalStateException: mc.player.serverBrand must not be null
	at me.zeroeightsix.kami.module.modules.client.InfoOverlay.infoContents(InfoOverlay.kt:94)
	at me.zeroeightsix.kami.gui.kami.KamiGUI.lambda$initializeGUI$1(KamiGUI.java:276)
	at me.zeroeightsix.kami.gui.rgui.GUI.lambda$callTick$8(GUI.java:334)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at me.zeroeightsix.kami.gui.rgui.GUI.callTick(GUI.java:334)
	at me.zeroeightsix.kami.gui.rgui.GUI.callTick(GUI.java:332)
	at me.zeroeightsix.kami.event.ForgeEventProcessor.onTick(ForgeEventProcessor.kt:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_ForgeEventProcessor_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path, and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.zeroeightsix.kami.module.modules.client.InfoOverlay.infoContents(InfoOverlay.kt:94)
	at me.zeroeightsix.kami.gui.kami.KamiGUI.lambda$initializeGUI$1(KamiGUI.java:276)
	at me.zeroeightsix.kami.gui.rgui.GUI.lambda$callTick$8(GUI.java:334)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at me.zeroeightsix.kami.gui.rgui.GUI.callTick(GUI.java:334)
	at me.zeroeightsix.kami.gui.rgui.GUI.callTick(GUI.java:332)
	at me.zeroeightsix.kami.event.ForgeEventProcessor.onTick(ForgeEventProcessor.kt:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_ForgeEventProcessor_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

```

**Comment by MrGeorgen** [comment]
I'm not sure what caused this. The server brand sould be vanilla

**Comment by YeetyDankEngine** [comment]
and for me sigma doesn't work

**Comment by YeetyDankEngine** [comment]
spits out an error in a different language

**Comment by MrGeorgen** [comment]
I'll close because it is non vanilla, but if someone figures it out make a pr
