### ISSUE TITLE
ELIFECYCLE Error, send help!

### ISSUE THREAD

**Issue by RainbowRogue** [themoonisacheese/2bored2wait#155]
> 2bored2wait@1.0.0 start C:\Users\redacted\OneDrive\Desktop\2bored2wait-master\2bored2wait-master
> node main.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node-json-minify'
Require stack:
- C:\Users\redacted\OneDrive\Desktop\2bored2wait-master\2bored2wait-master\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\redacted\OneDrive\Desktop\2bored2wait-master\2bored2wait-master\main.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\redacted\\OneDrive\\Desktop\\2bored2wait-master\\2bored2wait-master\\main.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\redacted\AppData\Roaming\npm-cache\_logs\2020-12-16T22_47_23_944Z-debug.log

is what comes up

**Comment by RainbowRogue** [comment]
if it something to do with ports idk how to do it so could somebody give me a tut of how to do it

**Comment by MrGeorgen** [comment]
the module node-json-minify is not installed. did you run `npm install`

**Comment by RainbowRogue** [comment]
yeah i did

**Comment by MrGeorgen** [comment]
> yeah i did (edit: ive tried multiple times and all of them show the node-json-minify module not installed.)

than it is an issue of npm
