### ISSUE TITLE
Error listening EADDRINUSE

### ISSUE THREAD

**Issue by HenriqueDLofcc** [themoonisacheese/2bored2wait#161]
When i run the command node discordBot.js and start the queue in cmd shows the message 

Activity set to Not queueing.
Activity set to Starting queue.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:25565
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (C:\Users\Henrique\Desktop\2b2t\2bored2wait\node_modules\minecraft-protocol\src\server.js:44:12)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 25565
}

**Comment by HenriqueDLofcc** [comment]
I solucioned the problem. Just give the command star in discord after start in localhost

**Comment by YeetyDankEngine** [comment]
@HenriqueDLofcc close the issue

**Comment by MrGeorgen** [comment]
there is no discordBot.js file in this project
