### ISSUE TITLE
I get an error after running npm start

### ISSUE THREAD

**Issue by Natuneko** [themoonisacheese/2bored2wait#165]
After running npm start, I got the following error

```
> 2bored2wait@1.0.0 start
> node main.js


/home/natu/2b2t/2bored2wait/main.js:23
        throw("error loading config file:\n" + err);
        ^
error loading config file:
SyntaxError: Unexpected token D in JSON at position 14
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code 1
npm ERR! path /home/natu/2b2t/2bored2wait
npm ERR! command failed
npm ERR! command sh -c node main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/natu/.npm/_logs/2020-12-29T12_53_39_425Z-debug.log
```
Is there any improvement

**Comment by Natuneko** [comment]
The error has changed

```
> 2bored2wait@1.0.0 start
> node main.js

$ node:events:353
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1278:21)
    at listenInCluster (node:net:1343:12)
    at Server.listen (node:net:1429:7)
    at Object.createServer (/home/natu/2b2t/2bored2wait/webserver.js:53:6)
    at Object.<anonymous> (/home/natu/2b2t/2bored2wait/main.js:88:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1322:8)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
npm ERR! code 1
npm ERR! path /home/natu/2b2t/2bored2wait
npm ERR! command failed
npm ERR! command sh -c node main.js

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/natu/.npm/_logs/2020-12-29T23_17_32_235Z-debug.log

**Comment by Natuneko** [comment]
Solved by setting webport in config.json to 8080

**Comment by klokwert** [comment]
You can also try to use sudo as you will then have rights to open ports under 1024

**Comment by AverageComet250** [comment]
It might be that port 80 isn't being released properly and thus 2b2w can't use the port again until the computer is reset to release all ports. Issue #166 would fix this as well because it detects port the set port as unusable and automatically uses another port.
