### ISSUE TITLE
npm start error ELIFECYCLE

### ISSUE THREAD

**Issue by ISmile008** [themoonisacheese/2bored2wait#168]
C:\Users\Admin\Desktop\2bored2wait-master>npm start

> 2bored2wait@1.0.0 start C:\Users\Admin\Desktop\2bored2wait-master
> node main.js

C:\Users\Admin\Desktop\2bored2wait-master\main.js:25
let finishedQueue = !config.minecraftserver.is2b2t;
                                            ^

TypeError: Cannot read property 'is2b2t' of undefined
    at Object.<anonymous> (C:\Users\Admin\Desktop\2bored2wait-master\main.js:25:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-12-30T14_31_33_436Z-debug.log

C:\Users\Admin\Desktop\2bored2wait-master>

**Comment by MrGeorgen** [comment]
settings in your config.json are missing
