### ISSUE TITLE
I have problem after start npm start

### ISSUE THREAD

**Issue by Sksiis** [themoonisacheese/2bored2wait#183]
internal/modules/cjs/loader.js:458
  throw e;
  ^

Error: Package exports for '/data/data/com.termux/files/home/2lazy2wait/2lazy2wait-patch-1/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:455:13)
    at resolveExports (internal/modules/cjs/loader.js:388:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:487:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:782:27)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/2lazy2wait/2lazy2wait-patch-1/node_modules/yggdrasil/lib/Client.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10) {
  code: 'MODULE_NOT_FOUND'
}
Help  i'm use termux phone meizu m6s

**Comment by MrGeorgen** [comment]
you are using 2lazy2wait which is not useful anymore because 2b2w also has an discord bot. If still want to use 2lazy2wait report the error to 2lazy2wait
