### ISSUE TITLE
Error in main.js 

### ISSUE THREAD

**Issue by SKITLSE** [themoonisacheese/2bored2wait#186]
/data/data/com.termux/files/home/2bored2wait/main.js:298
        if (config.discordBot) dc.user.setActivity(true);
                                       ^

TypeError: Cannot read property 'setActivity' of null
    at activity (/data/data/com.termux/files/home/2bored2wait/main.js:298:33)
    at join (/data/data/com.termux/files/home/2bored2wait/main.js:153:2)
    at Timeout.startQueuing [as _onTimeout] (/data/data/com.termux/files/home/2bored2wait/main.js:144:2)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Help me version nodejs 12.13.0-2

**Comment by SKITLSE** [comment]
New error 
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:25565
    at Server.setupListenHandle [as _listen2] (net.js:1300:14)
    at listenInCluster (net.js:1348:12)
    at doListen (net.js:1487:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processTimers (internal/timers.js:472:9)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (/data/data/com.termux/files/home/wait/node_modules/minecraft-protocol/src/server.js:44:12)
    at Server.emit (events.js:210:5)
    at emitErrorNT (net.js:1327:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processTimers (internal/timers.js:472:9) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 25565
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1

**Comment by SKITLSE** [comment]
I fix this by i install inventory_cache version
