### ISSUE TITLE
program can not connect to 2b2t

### ISSUE THREAD

**Issue by rand0musername5** [themoonisacheese/2bored2wait#197]
c:\2b2t\2bored2wait-master>npm start

> 2bored2wait@1.0.0 start c:\2b2t\2bored2wait-master
> node main.js

Connection error by 2b2t server. Error message: Error: getaddrinfo ENOTFOUND 2b2t.org Reconnecting...
Connection reset by 2b2t server. Reconnecting...
Reconnecting...
Reconnecting...
$

**Comment by rand0musername5** [comment]
Oh never mind. It worked

**Comment by rand0musername5** [comment]
The program starts queue. But the button didn't change the colour. When i pressed it again program crashes.

c:\2b2t\2bored2wait-master>npm start

> 2bored2wait@1.0.0 start c:\2b2t\2bored2wait-master
> node main.js

Connection error by 2b2t server. Error message: Error: getaddrinfo ENOTFOUND 2b2t.org Reconnecting...
Connection reset by 2b2t server. Reconnecting...
Reconnecting...
Reconnecting...

$ update
Position: 744  Estimated time until login: 6h 12m
P: 743 E: 6h 11m - (email)@gmail.com
P: 742 E: 6h 11m - (email)@gmail.com
P: 741 E: 6h 10m - (email)@gmail.com
P: 740 E: 6h 10m - (email)@gmail.com
$ play 12PM
Unknown command
P: 739 E: 6h 9m - (email)@gmail.com
$ play 12:00
The perfect time to start the queue will be calculated, so you can play at 12:00
P: 737 E: 6h 8m - (email)@gmail.com
P: 736 E: 6h 8m - (email)@gmail.com
$ events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:25565
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (c:\2b2t\2bored2wait-master\node_modules\minecraft-protocol\src\server.js:44:12)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 25565
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alekd\AppData\Roaming\npm-cache\_logs\2021-01-30T22_03_52_742Z-debug.log

c:\2b2t\2bored2wait-master>
