### ISSUE TITLE
error on node 12 and below

### ISSUE THREAD

**Issue by CarterSullivan** [themoonisacheese/2bored2wait#201]
I configured the config.json, but when I run 
sudo npm start
and
npm start
I get this error:

/home/carter/2b2t/2bored2wait/node_modules/yggdrasil/lib/Client.js:37
            options.token = options.token ?? uuid_1.default.v4();
                                           ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/carter/2b2t/2bored2wait/node_modules/yggdrasil/lib/index.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/carter/.npm/_logs/2021-02-04T14_49_02_268Z-debug.log

**Comment by MrGeorgen** [comment]
seems like does not work with node.js 10 and 12. for node 14 it does work as
you see here at the [test](https://github.com/themoonisacheese/2bored2wait/runs/1800982960)

**Comment by MrGeorgen** [comment]
I have opened an [issue](https://github.com/PrismarineJS/node-yggdrasil/issues/60)
