### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Villygrimm** [themoonisacheese/2bored2wait#204]
Hello I have a problem I have everything set up and when I start npm start I have this error.

Error: listen EADDRNOTAVAIL: address not available 217.79.31.8:25565
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (C:\Users\Zver\Desktop\2bored2wait-master\node_modules\minecraft-protocol\src\server.js:44:12)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRNOTAVAIL',
  errno: -4090,
  syscall: 'listen',
  address: '217.79.31.8',
  port: 25565
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zver\AppData\Roaming\npm-cache\_logs\2021-02-08T07_29_03_729Z-debug.log

**Comment by MrGeorgen** [comment]
did you change the address the server listenes on?

**Comment by Villygrimm** [comment]
Yes i change but if I enter the address 0.0.0.0 then I have a slightly different error there instead, address use

**Comment by MrGeorgen** [comment]
> Yes i change but if I enter the address 0.0.0.0 then I have a slightly different error there instead, address use

you can not listen on a random public ip. Post your error if you change it
back 0.0.0.0
