### ISSUE TITLE
Can’t start the bot, for no reason

### ISSUE THREAD

**Issue by plebeo** [themoonisacheese/2bored2wait#228]
Yesterday it was working like usual. Today I wake up and it crashes whenever I start it, with this message.
![image](https://user-images.githubusercontent.com/72709996/110092323-c4ca6980-7d99-11eb-84a8-300a7cff4373.jpeg)

**Comment by wylie39** [comment]
Could you please post the full error message?

**Comment by czho** [comment]
got the same error



Connection reset by 2b2t server. Reconnecting...
$ 
Reconnecting... 
$ start
Queue is starting up
$ /home/czho/Documents/GitHub/2bored2wait/main.js:163
                                        let positioninqueue = headermessage.text.split("\n")[5].substring(25);
                                                                                               ^

TypeError: Cannot read property 'substring' of undefined
    at Client.<anonymous> (/home/czho/Documents/GitHub/2bored2wait/main.js:163:61)
    at Client.emit (node:events:388:22)
    at FullPacketParser.<anonymous> (/home/czho/Documents/GitHub/2bored2wait/node_modules/minecraft-protocol/src/client.js:90:12)
    at FullPacketParser.emit (node:events:376:20)
    at addChunk (/home/czho/Documents/GitHub/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/czho/Documents/GitHub/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/czho/Documents/GitHub/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/home/czho/Documents/GitHub/2bored2wait/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/home/czho/Documents/GitHub/2bored2wait/node_modules/protodef/src/serializer.js:89:10)
    at FullPacketParser.Transform._read (/home/czho/Documents/GitHub/2bored2wait/node_modules/readable-stream/lib/_stream_transform.js:177:10)
npm ERR! code 1
npm ERR! path /home/czho/Documents/GitHub/2bored2wait
npm ERR! command failed
npm ERR! command sh -c node main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/czho/.npm/_logs/2021-03-06T02_01_57_333Z-debug.log
czho@czho:~/Documents/GitHub/2bored2wait$ npm start

**Comment by ChillerDragon** [comment]
"for no reason" :D

**Comment by MrGeorgen** [comment]
this error accurs when the queue psoition is not in the tablist. did you
change the hostname?

**Comment by plebeo** [comment]
This error happened over night, nothing changed.

**Comment by czho** [comment]
> this error accurs when the queue psoition is not in the tablist. did you
> change the hostname?

I did not, hause might have changed something about the tab list when first joining queue.
Another clue is that it doesn't always happen to me at least.

**Comment by MrGeorgen** [comment]
https://github.com/themoonisacheese/2bored2wait/commit/80b643b11e11834475251ec62a6cb08569a1cadb fixed that
