### ISSUE TITLE
Error before even reaching login

### ISSUE THREAD

**Issue by TooVeryIcey** [themoonisacheese/2bored2wait#24]
When running `npm start` the following is displayed:

```
`> 2bored2wait@1.0.0 start C:\Users\Zachary 2VeryIcey\,Applications\2bored2wait-master\2bored2wait-master
> node main.js

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:80' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
```

**Comment by themoonisacheese** [comment]
it would seem your computer has trouble opening a browser window automatically.
set openBrowserOnStart in config.json to false, and open a browser window manually to go to http://localhost .

**Comment by TooVeryIcey** [comment]
> 
> 
> it would seem your computer has trouble opening a browser window automatically.
> set openBrowserOnStart in config.json to false, and open a browser window manually to go to http://localhost .

Okay, thank you!
