### ISSUE TITLE
Error in main.js > let positioninqueue

### ISSUE THREAD

**Issue by HyCore** [themoonisacheese/2bored2wait#260]
Hi, is it possible to add a variable to avoid this error and just continue without "let positionqueue..."
```
$ /var/www/html/2bored2wait/main.js:190
                                        let positioninqueue = headermessage.text.split("\n")[5].substring(25);
                                                                                               ^

TypeError: Cannot read property 'substring' of undefined
    at Client.<anonymous> (/var/www/html/2bored2wait/main.js:190:61)
    at Client.emit (events.js:327:22)
    at FullPacketParser.<anonymous> (/var/www/html/2bored2wait/node_modules/minecraft-protocol/src/client.js:90:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (/var/www/html/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/var/www/html/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/var/www/html/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/var/www/html/2bored2wait/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/var/www/html/2bored2wait/node_modules/protodef/src/serializer.js:89:10)
    at FullPacketParser.Transform._read (/var/www/html/2bored2wait/node_modules/readable-stream/lib/_stream_transform.js:177:10)

```
It would avoid crash when you are in the 2b2t premium queue.

**Comment by czho** [comment]
It does this when you try to use 2b2w when prio queue is 0 and you instantly get in, maby we should try catch this to avoid the crash

**Comment by HyCore** [comment]
is there no way to fix this ? cuz yes it's when prio is at 0 but there should be a way to make it work even if it's at 0, like if return incorrect value then return player connected.
somthing like that

**Comment by themoonisacheese** [comment]
There are lots of ways 2b2t can be a bitch and not give expected data, so the best I can think of is to say your place is "None" if I can't read it. Also, the console will get an error message, and while it shouldn't happen, it is possible for the console to be spammed, so be careful about your log file sizes.
