### ISSUE TITLE
after a short time an error message comes up 

### ISSUE THREAD

**Issue by gabrielmaster123** [themoonisacheese/2bored2wait#261]
$ 27022.063373060482
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:25565
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (C:\Users\Unterricht\Downloads\2bored2wait-master\2bored2wait-master\node_modules\minecraft-protocol\src\server.js:44:12)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 25565
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Unterricht\AppData\Roaming\npm-cache\_logs\2021-04-19T05_35_00_364Z-debug.log
^that is the message

**Comment by MrGeorgen** [comment]
do you already run a mc server on 25565?

**Comment by gabrielmaster123** [comment]
no I dont even know how to run a minecraft server, or any server.

**Comment by czho** [comment]
are you running multiple 2b2w programs on the same pc?

**Comment by gabrielmaster123** [comment]
No

**Comment by gabrielmaster123** [comment]
No, I didn't.

**Comment by rob9315** [comment]
this message tells you that the port is already used, hence it crashes. This is not an issue with 2bored2wait or was fixed.
