### ISSUE TITLE
Getting crashed while crafting on the proxy

### ISSUE THREAD

**Issue by HyCore** [themoonisacheese/2bored2wait#267]
Wierd indeed:
`java.lang.NullPointerException: Ticking screen
    at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:172)
    at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193942_g(GuiRecipeBook.java:235)
    at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193957_d(GuiRecipeBook.java:224)
    at net.minecraft.client.gui.inventory.GuiCrafting.func_73876_c(SourceFile:51)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1779)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by MrGeorgen** [comment]
after reconnecting the recipe book data is desynced. However that should not
cause a crash

**Comment by etiaro** [comment]
I am experiencing same problem recently, it's almost unplayable. Is there any chance to get it synced?

**Comment by HyCore** [comment]
Yeah it's appending again on the last  commit, (probably other one, I didn't check) but when the 2b2w reconnect in loop after a restart for exemple, if you have a client that, also reconnect on 2b2w during this time, it crash, with a "address already in use" error.
