### ISSUE TITLE
Error after running `npm start`

### ISSUE THREAD

**Issue by GameCenterJerry** [themoonisacheese/2bored2wait#274]
Title says it all, Left blank for minecraft folder, discord bot token and something else.

```
> mcproxy@1.0.0 postinstall /Users/me/Downloads/2bored2wait-master/node_modules/mcproxy
> npm run build

$ (node:28056) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/Users/me/Downloads/2bored2wait-master/node_modules/discord.js/src/client/Client.js:206:52)
    at askForSecrets (/Users/me/Downloads/2bored2wait-master/main.js:106:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by etiaro** [comment]
Well, did you take a look into config? You probably just have to change discordBot: false

**Comment by MrGeorgen** [comment]
discord bot is started even if it is disabled
