### ISSUE TITLE
UnhandledPromiseRejectionWarning on Windows 10

### ISSUE THREAD

**Issue by lufog** [themoonisacheese/2bored2wait#296]
What I'm typing:
```
Do you want to use launcher account data? Y or N [N]: n
Account type, mojang (1) or microsoft (2) [1]: 1
Email: <my mj email>
Password: <my mj password>
BotToken, leave blank if not using discord []:
Save login for later use? Y or N [N]: y
```
What  2b2w shows me:
```
$ (node:1604) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\Aleksey\Desktop\node_modules\discord.js\src\client\Client.js:206:52)
    at askForSecrets (C:\Users\Aleksey\Desktop\main.js:89:6)
    at Object.<anonymous> (C:\Users\Aleksey\Desktop\main.js:124:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\Users\Aleksey\Desktop\check.js:27:4
(Use `2bored2wait-windows-x86-0.1.19 --trace-warnings ...` to show where the warning was created)
(node:1604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lufog** [comment]
Ok, string `leave blank if not using discord` confused me.

**Comment by KozmikNano** [comment]
Yeah, we currently have to work for a fix on that. Sorry about the inconvenience.

**Comment by themoonisacheese** [comment]
fixed as of https://github.com/themoonisacheese/2bored2wait/commit/5ff201b369253d0bda3bd0793c62df2ce32ba1d5
