### ISSUE TITLE
Server crashes unexpectedly

### ISSUE THREAD

**Issue by Rattlyy** [themoonisacheese/2bored2wait#31]
Don't know what happened. I was 40 on 350 queue then saw this on site:
![image](https://user-images.githubusercontent.com/40183121/67158292-a7c50000-f336-11e9-8c2c-56f4de0c7d9d.png).

Seemed a bit strange, so, decided to check the console.
This is the error:
<code> err { Error: Serialization error for play.toServer : SizeOf error for name : undefined is not in the mappings value
    at ProtoDef.sizeOfMapper (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\datatypes\utils.js:59:34)
    at ProtoDef.sizeOf (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\protodef.js:127:31)
    at tryDoc (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\datatypes\structures.js:72:30)
    at tryCatch (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\utils.js:50:16)
    at tryDoc (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\utils.js:54:10)
    at typeArgs.reduce (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\datatypes\structures.js:72:12)
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\datatypes\structures.js:71:25)
    at ProtoDef.sizeOf (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\protodef.js:40:67)
    at ProtoDef.sizeOf (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\protodef\src\protodef.js:127:31) field: 'play.toServer' }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:25565
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at doListen (net.js:1505:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) </code>

**Comment by zRattly** [comment]
Update:
Tryed reinstalling. Now it gives me this:
<code>
err SyntaxError: Unexpected token < in JSON at position 0                                                                   at JSON.parse (<anonymous>)                                                                                             at C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\yggdrasil\lib\utils.js:28:23               at IncomingMessage.<anonymous> (C:\Users\User\Creative Cloud Files\Desktop\2bored2wait-0.0.1\node_modules\phin\lib\phin.compiled.js:1:2162)                                                                                                     at emitNone (events.js:111:20)                                                                                          at IncomingMessage.emit (events.js:208:7)                                                                               at endReadableNT (_stream_readable.js:1064:12)                                                                          at _combinedTickCallback (internal/process/next_tick.js:138:11)                                                         at process._tickCallback (internal/process/next_tick.js:180:9)
</code>

**Comment by themoonisacheese** [comment]
the first error was caused by something already using the port specified in the config for minecraft. maybe you have another server running, or maybe you launched it twice?

the second looks like bad data was recieved from the server. please try again.

**Comment by zRattly** [comment]
Yeah, tryed again alot.
Seems like smth broke

**Comment by zRattly** [comment]
@themoonisacheese bump

**Comment by themoonisacheese** [comment]
would you happen to play using a wifi hotspot?

**Comment by zRattly** [comment]
nope

**Comment by themoonisacheese** [comment]
then I have absolutely no clue. the only thing left is your firewall, or the default windows one if you don't have any, but that shouldn't cause this type of error.

**Comment by sijanec** [comment]
maybe try on linux as root, that should give you full perms and probably avoid problems with iptables and other stuff... Windows can sometimes prompt you with a dialog box and checkboxes for private and public networks, I usually check both and hit okay... Idk how it determines if a network is public or private...

**Comment by YeetyDankEngine** [comment]
nope

**Comment by AverageComet250** [comment]
Windows requires you to say if a network is public or private and sets new networks to public by default (at least on win 10). On windows 10 you have to open your WiFi properties (place where you can find default gateway and private IP) and change it from public to private.

**Comment by MrGeorgen** [comment]
I guess it is fixed
