### ISSUE TITLE
Error when npm start

### ISSUE THREAD

**Issue by PerchunPak** [themoonisacheese/2bored2wait#344]
```
E:\servers\programming\2b2w\2bored2wait>npm start
(node:8552) ExperimentalWarning: The fs.promises API is experimental

> 2bored2wait@0.1.43 start
> node check.js

(node:10648) UnhandledPromiseRejectionWarning: E:\servers\programming\2b2w\2bored2wait\main.js:95
                dc.login(discordBotToken??config.get('BotToken')).catch(()=>{
                                         ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at feed.items.every.item (E:\servers\programming\2b2w\2bored2wait\check.js:31:16)
    at Array.every (<anonymous>)
    at E:\servers\programming\2b2w\2bored2wait\check.js:18:16
(node:10648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rob9315** [comment]
You are running a too old version of nodejs, please update

**Comment by hari01584** [comment]
Use node version 14+ or else you will be getting many of these kinds of errors.

**Comment by rob9315** [comment]
If you continue to experience issues with a new version of node, please reopen this issue.
