### ISSUE TITLE
Error on PopOS when opening the linux file version

### ISSUE THREAD

**Issue by InfinteSial** [themoonisacheese/2bored2wait#358]
rror: listen EADDRINUSE: address already in use 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080

**Comment by qualk** [comment]
That means either 2 instances of 2b2w are running, or something else on your computer is using port 8080

**Comment by KozmikNano** [comment]
That is completely true! To fix this look for the default config file and look for the web port section. Change 8080 to 81 (assuming 80 is already connected). Save and try to run again. If you don’t see this file then just install 2b2w using the second method!

**Comment by qualk** [comment]
Wow I was correct about something :)
