### ISSUE TITLE
 for some reason it does not start

### ISSUE THREAD

**Issue by Lol437** [themoonisacheese/2bored2wait#387]
Hello, when I try to run I get an error
> 2bored2wait@1.2.0 test /home/lokomanako/Рабочий стол/2б2т бот/2bored2wait
> node test.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node-json-minify'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/lokomanako/Рабочий стол/2б2т бот/2bored2wait/util.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! Test failed.  See above for more details.

help please.

**Comment by themoonisacheese** [comment]
Did you properly run npm install?

**Comment by Lol437** [comment]
but yes I forgot to run npm install
and now where do you need to lead your tokin
I now have this error
i drove my teken in main.js but nothing changed
> 2bored2wait@1.2.0 start /home/lokomanako/Рабочий стол/2б2т бот/2bored2wait
> node check.js

(node:35244) UnhandledPromiseRejectionWarning: /home/lokomanako/Рабочий стол/2б2т бот/2bored2wait/main.js:96
		dc.login(discordBotToken??config.get('BotToken')).catch(()=>{
		                         ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at feed.items.every.item (/home/lokomanako/Рабочий стол/2б2т бот/2bored2wait/check.js:31:16)
    at Array.every (<anonymous>)
    at /home/lokomanako/Рабочий стол/2б2т бот/2bored2wait/check.js:18:16
(node:35244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rob9315** [comment]
please update your nodejs version to at least 14, best to be on the latest one

**Comment by Lol437** [comment]
thank you very much, everything worked for me
