### ISSUE TITLE
how fix this error

### ISSUE THREAD

**Issue by ObsidianOption** [themoonisacheese/2bored2wait#399]
AssertionError [ERR_ASSERTION]: Please specify an "authTitle" in Authflow constructor
    at MicrosoftAuthFlow.getMinecraftJavaToken (/home/gnukong/2bored2wait/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:135:5)
    at Object.authenticate (/home/gnukong/2bored2wait/node_modules/minecraft-protocol/src/client/microsoftAuth.js:12:59)
    at Object.createClient (/home/gnukong/2bored2wait/node_modules/minecraft-protocol/src/createClient.js:38:19)
    at Object.createBot (/home/gnukong/2bored2wait/node_modules/mineflayer/lib/loader.js:95:35)
    at new Conn (/home/gnukong/2bored2wait/node_modules/@rob9315/mcproxy/lib/conn.js:25:33)
    at startQueuing (/home/gnukong/2bored2wait/main.js:203:9)
    at userInput (/home/gnukong/2bored2wait/main.js:385:4)
    at /home/gnukong/2bored2wait/main.js:169:3
    at Interface._onLine (node:readline:485:5)
    at Interface._line (node:readline:864:8) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='

**Comment by rob9315** [comment]
fixed with latest commit
