### ISSUE TITLE
Proxy crashes when joined

### ISSUE THREAD

**Issue by cybr-dev** [themoonisacheese/2bored2wait#419]
The proxy crashes when i try to join.

Im using the raspi setup with the latest version of code.
 
 Error Message:
```
 /home/**/2bored2wait/node_modules/@rob9315/mcproxy/lib/packets.js:154
        ...Object.values(bot._blockEntities).reduce((packets, { x, y, z, raw: nbtData }) => {
                  ^

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at generatePackets (/home/pi/2bored2wait/node_modules/@rob9315/mcproxy/lib/packets.js:154:19)
    at Conn.generatePackets (/home/pi/2bored2wait/node_modules/@rob9315/mcproxy/lib/conn.js:71:46)
    at Conn.sendPackets (/home/pi/2bored2wait/node_modules/@rob9315/mcproxy/lib/conn.js:67:14)
    at /home/pi/2bored2wait/main.js:323:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by cybr-dev** [comment]
It happesn with different clients and also with @[rob9315](https://github.com/rob9315) rewrite as the problem seems to be in the mcproxy library

**Comment by rob9315** [comment]
has been fixed now in the `mcproxy` lib, update pushed to this repo as well
