### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by WinsDominoes** [themoonisacheese/2bored2wait#42]
When I started the proxy. I typed the correct email and password, and i changed the port to 8087 
and.. I got this this error when I started.

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:25565
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Server.<anonymous> (C:\Users\WinsVideo\Desktop\2bored2wait-master\node_modules\minecraft-protocol\src\server.js:45:12)
    at Server.emit (events.js:198:13)
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\-\-\AppData\Roaming\npm-cache\_logs\2020-02-22T11_46_48_592Z-debug.log

**Comment by themoonisacheese** [comment]
try chaanging the minecraft port to something higher.
if that doesnt work, edit main.js at line 103 and change "0.0.0.0" to "127.0.0.1"

**Comment by WinsDominoes** [comment]
It still doesn't work. I also use this PC as a web server. Does it affect the proxy?

**Comment by WinsDominoes** [comment]
I works now, Thank you!
