### ISSUE TITLE
details: { statusCode: 401, reason: 'UNAUTHORIZED' }

### ISSUE THREAD

**Issue by ItsOnlyMyUsername** [themoonisacheese/2bored2wait#426]
I'm trying to login to my minecraft account through microsoft. I get this error, the data is correct and I even double-checked a couple of times both on the site and in the launcher.

and here is the error:
```
XboxReplayError: Invalid credentials.
    at Object.unauthorized (C:\Users\PC\Desktop\2bored2wait\node_modules\@xboxreplay\errors\dist\index.js:25:74)
    at C:\Users\PC\Desktop\2bored2wait\node_modules\@xboxreplay\xboxlive-auth\dist\core\live\index.js:71:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async XboxTokenManager.doReplayAuth (C:\Users\PC\Desktop\2bored2wait\node_modules\prismarine-auth\src\TokenManagers\XboxTokenManager.js:133:31)
    at async MicrosoftAuthFlow.getXboxToken (C:\Users\PC\Desktop\2bored2wait\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:117:20)
    at async retry.xbl.forceRefresh (C:\Users\PC\Desktop\2bored2wait\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:157:22)
    at async retry (C:\Users\PC\Desktop\2bored2wait\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:24:14)
    at async MicrosoftAuthFlow.getMinecraftJavaToken (C:\Users\PC\Desktop\2bored2wait\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:156:7)
    at async Object.authenticate (C:\Users\PC\Desktop\2bored2wait\node_modules\minecraft-protocol\src\client\microsoftAuth.js:17:44) {
  __XboxReplay__: true,
  details: { statusCode: 401, reason: 'UNAUTHORIZED' }
}
```

**Comment by ItsOnlyMyUsername** [comment]
Thanks
