### ISSUE TITLE
its not working and im not sure why

### ISSUE THREAD

**Issue by assassin-cerw** [themoonisacheese/2bored2wait#427]
$ Sign in failed, try removing the password field

(node:22908) UnhandledPromiseRejectionWarning: XboxReplayError: Invalid credentials.
    at Object.unauthorized (C:\Users\hoesm\OneDrive\Desktop\node_modules\@xboxreplay\errors\dist\index.js:25:74)
    at C:\Users\hoesm\OneDrive\Desktop\node_modules\@xboxreplay\xboxlive-auth\dist\core\live\index.js:71:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async XboxTokenManager.doReplayAuth (C:\Users\hoesm\OneDrive\Desktop\node_modules\prismarine-auth\src\TokenManagers\XboxTokenManager.js:132:31)
    at async MicrosoftAuthFlow.getXboxToken (C:\Users\hoesm\OneDrive\Desktop\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:116:20)
    at async retry.xbl.forceRefresh (C:\Users\hoesm\OneDrive\Desktop\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:157:22)
    at async retry (C:\Users\hoesm\OneDrive\Desktop\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:23:14)
    at async MicrosoftAuthFlow.getMinecraftJavaToken (C:\Users\hoesm\OneDrive\Desktop\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:156:7)
    at async Object.authenticate (C:\Users\hoesm\OneDrive\Desktop\node_modules\minecraft-protocol\src\client\microsoftAuth.js:17:44)
(Use `2bored2wait-windows-x64-3.0.5 --trace-warnings ...` to show where the warning was created)
(node:22908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

if someone could help me it would be a big help

**Comment by KozmikNano** [comment]
Go to your config file and remove your password from it. Now rerun, and teem me how it goes :)

**Comment by assassin-cerw** [comment]
thanks it worked

**Comment by KozmikNano** [comment]
No problem! Glad I could help :)
