### ISSUE TITLE
Incorrect Password (Awaiting Response)

### ISSUE THREAD

**Issue by 1Chip1** [themoonisacheese/2bored2wait#455]
Hey, I downloaded 2b2w and tried to start it, everything was working fine but after i typed start it crashed after 4 to 10 seconds with no error message

**Comment by 1Chip1** [comment]
``C:\snapshot\2bored2wait\node_modules\@xboxreplay\errors\dist\index.js:25
    unauthorized: (message = 'Unauthorized', reason = 'UNAUTHORIZED') => new XboxReplayError(message, {
                                                                         ^

XboxReplayError: Invalid credentials.
    at Object.unauthorized (C:\snapshot\2bored2wait\node_modules\@xboxreplay\errors\dist\index.js:25:74)
    at C:\snapshot\2bored2wait\node_modules\@xboxreplay\xboxlive-auth\dist\core\live\index.js:71:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async XboxTokenManager.doReplayAuth (C:\snapshot\2bored2wait\node_modules\prismarine-auth\src\TokenManagers\XboxTokenManager.js:130:31)
    at async MicrosoftAuthFlow.getXboxToken (C:\snapshot\2bored2wait\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:117:20)
    at async C:\snapshot\2bored2wait\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:157:22
    at async retry (C:\snapshot\2bored2wait\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:24:14)
    at async MicrosoftAuthFlow.getMinecraftJavaToken (C:\snapshot\2bored2wait\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:156:7)
    at async Object.authenticate (C:\snapshot\2bored2wait\node_modules\minecraft-protocol\src\client\microsoftAuth.js:17:44) {
  __XboxReplay__: true,
  details: { statusCode: 401, reason: 'UNAUTHORIZED' }
}``

**Comment by KozmikNano** [comment]
Appears to be a login issue, go into your local.json and remove your password that you typed. Make sure to leave the `password: “”,` though

**Comment by 1Chip1** [comment]
what directory is local.json?

**Comment by KozmikNano** [comment]
For the manual install it is going to be inside config folder. For the executable it will be under the ~/.config/2bored2wait folder (Linux) and C:\Users\username\.config\2bored2wait\

**Comment by KozmikNano** [comment]
What operating system?

**Comment by 1Chip1** [comment]
Windows

**Comment by KozmikNano** [comment]
Sorry for the late response but the folder is located here: `C:\Users\USERNAME\AppData\Roaming\2bored2wait\Config\`

**Comment by rob9315** [comment]
assuming fixed
