### ISSUE TITLE
I cant open localhost:8080

### ISSUE THREAD

**Issue by mrlolua19** [themoonisacheese/2bored2wait#484]
When I try to open it localhost:8080 is simply infinity loading. And on node.js there is this error:
Error: ENOENT: no such file or directory, open 'webserver/index.html'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:796:32)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1082:36)
    at Server.<anonymous> (C:\snapshot\2bored2wait\webserver\webserver.js)
    at Server.emit (node:events:527:28)
    at parserOnIncoming (node:_http_server:956:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'webserver/index.html'
}

**Comment by KozmikNano** [comment]
This is a known issue with the executables. Please use the alternative install or just use the cli & discord bot.
