### ISSUE TITLE
i keep getting this error on discord.js

### ISSUE THREAD

**Issue by Framdark** [themoonisacheese/2bored2wait#49]
Error: Cannot find module 'sleep'
Require stack:
- C:\Users\dfgot\Desktop\2lazy2wait-master\discordbot.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\dfgot\Desktop\2lazy2wait-master\discordbot.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\dfgot\\Desktop\\2lazy2wait-master\\discordbot.js' ]

**Comment by themoonisacheese** [comment]
this version of the tool does not include nor support any form of discord integration. please refer to the repo you downloaded this from.
