### ISSUE TITLE
The program went wrong?

### ISSUE THREAD

**Issue by TeacherLi07** [themoonisacheese/2bored2wait#516]
$ Error: ENOENT: no such file or directory, open 'webserver/index.html'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:796:32)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1082:36)
    at Server.<anonymous> (C:\snapshot\2bored2wait\webserver\webserver.js)
    at Server.emit (node:events:527:28)
    at parserOnIncoming (node:_http_server:956:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'webserver/index.html'
}

   ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━ Something Is Wrong ━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
   ┃                                                                          ┃
   ┃   Something went wrong! Feel free to contact us on discord or github!    ┃
   ┃                                                                          ┃
   ┃         Github: https://github.com/themoonisacheese/2bored2wait          ┃
   ┃                                                                          ┃
   ┃                  Discord: https://discord.next-gen.dev/                  ┃
   ┃                                                                          ┃
   ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Press any key to exit

After i ran the program, I typed in my email and verified. Then I opened http://localhost:8080 on my chrome, but the web page can't open, and the program said like this.
(poor English QAQ hope you can understand it)
v3.0.0  Windows10 amd64 
i just download the exe and double click

**Comment by TeacherLi07** [comment]
![image](https://user-images.githubusercontent.com/110473389/208109853-881df794-54b9-4c9e-8f4e-51f3654d06bc.png)

**Comment by TeacherLi07** [comment]
I tried anothor path, and it turns out not because of the chinese words in the path.

**Comment by TeacherLi07** [comment]
sooooooooooooory i see the same problem in the closed issue
:D
