### ISSUE TITLE
1.19 update

### ISSUE THREAD

**Issue by EloToJaa** [themoonisacheese/2bored2wait#567]
Are there any plans to update to 1.19 along with 2b2t?

**Comment by themoonisacheese** [comment]
Either it will be really simple and we just have to increment the version number, or it's more complicated and I won't fix it, personally.

PRs always welcome.

**Comment by rob9315** [comment]
It is not as easy as changing a number, someone has to change mcproxy's packet replication to mirror what vanilla 1.19 is doing. I'm not working on that either but anyone can fork and do it if they want to.

**Comment by jacobjake1** [comment]
> Either it will be really simple and we just have to increment the version number, or it's more complicated and I won't fix it, personally.
> 
> PRs always welcome.

I was getting this error when testing out 1.19.3

bot.autoEat.foodsByName = require('minecraft-data')(bot.version).foodsByName
^

TypeError: Cannot read properties of null (reading 'foodsByName')
at EventEmitter. (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\mineflayer-antiafk\node_modules\mineflayer-auto-eat\index.js:27:73)
at Object.onceWrapper (node:events:627:28)
at EventEmitter.emit (node:events:525:35)
at Client. (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\mineflayer\lib\plugins\health.js:13:11)
at Object.onceWrapper (node:events:628:26)
at Client.emit (node:events:525:35)
at FullPacketParser. (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\minecraft-protocol\src\client.js:91:12)
at FullPacketParser.emit (node:events:513:28)
at addChunk (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\readable-stream\lib_stream_readable.js:298:12)
at readableAddChunk (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\readable-stream\lib_stream_readable.js:280:11)

**Comment by themoonisacheese** [comment]
wontfix because we do not have plans to update.
c7ad99d00ee75126607aed036823801f7995f82c
