### ISSUE TITLE
1.19 progress?

### ISSUE THREAD

**Issue by jacobjake1** [themoonisacheese/2bored2wait#569]
Just checking to see if you are still working on updating this to 1.19 as I have this as a dependency and need it updated. It currently still works on 1.12.2, but when trying it on 1.19.3 I encounter this error:  

bot.autoEat.foodsByName = require('minecraft-data')(bot.version).foodsByName
^

TypeError: Cannot read properties of null (reading 'foodsByName')
at EventEmitter. (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\mineflayer-antiafk\node_modules\mineflayer-auto-eat\index.js:27:73)
at Object.onceWrapper (node:events:627:28)
at EventEmitter.emit (node:events:525:35)
at Client. (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\mineflayer\lib\plugins\health.js:13:11)
at Object.onceWrapper (node:events:628:26)
at Client.emit (node:events:525:35)
at FullPacketParser. (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\minecraft-protocol\src\client.js:91:12)
at FullPacketParser.emit (node:events:513:28)
at addChunk (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\readable-stream\lib_stream_readable.js:298:12)
at readableAddChunk (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\readable-stream\lib_stream_readable.js:280:11)

**Comment by themoonisacheese** [comment]
this is an issue in minecraft data.
even if it was in 2B2W, we do not plan on updating, although you are welcome to submit pull requests.
c7ad99d00ee75126607aed036823801f7995f82c
