### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Bear-03** [themoonisacheese/2bored2wait#64]
I'm getting this error when I press "Start queuing"

`err SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\jorge\Desktop\Stuff\Utilities\2bored2wait-master\node_modules\yggdrasil\lib\utils.js:28:23
    at IncomingMessage.<anonymous> (C:\Users\jorge\Desktop\Stuff\Utilities\2bored2wait-master\node_modules\phin\lib\phin.compiled.js:1:2100)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by MrGeorgen** [comment]
json syntax error
