### ISSUE TITLE
Error: Cannot find module './secrets.json'

### ISSUE THREAD

**Issue by joshrichards2001** [themoonisacheese/2bored2wait#66]
Error: Cannot find module './secrets.json'
Require stack:
- C:\Users\richa\OneDrive\Desktop\2bored2wait-master\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\richa\OneDrive\Desktop\2bored2wait-master\main.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\richa\\OneDrive\\Desktop\\2bored2wait-master\\main.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I have the secrets.json file so I am just really confused. Plus, I never had to rename the secrets.json.example file, there was only a secrets.json file there.

**Comment by themoonisacheese** [comment]
https://fileinfo.com/help/windows_10_show_file_extensions
