### ISSUE TITLE
discordOrigin is not defined when running npm start

### ISSUE THREAD

**Issue by Qbox683** [themoonisacheese/2bored2wait#97]
The following error occurs whenever I run npm start:
ReferenceError: discordOrigin is not defined
    at userInput (C:\Users\Heather\Desktop\2bored2wait-master\main.js:427:13)
    at C:\Users\Heather\Desktop\2bored2wait-master\main.js:85:3
    at Interface._onLine (readline.js:327:5)
    at Interface._line (readline.js:658:8)
    at Interface._ttyWrite (readline.js:1003:14)
    at ReadStream.onkeypress (readline.js:205:10)
    at ReadStream.emit (events.js:315:20)
    at emitKeys (internal/readline/utils.js:335:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1137:36)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Heather\AppData\Roaming\npm-cache\_logs\2020-09-24T15_04_25_021Z-debug.log
I made sure to change the host to 127.0.0.1 in main.js, renamed secrets.json.example to secrets.json, put in my information and discord bot token, and installed npm and git. I don't know what went wrong during this.

**Comment by MrGeorgen** [comment]
This a typo in the variable name. I'll make a pull request
